FROM bitnami/spark:3.1.2

# Change to root user
USER root

# Install requirements
COPY requirements_spark.txt ./requirements_spark.txt
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org -r requirements_spark.txt

# Change user
USER 1001