version: '3'

services:
  cassandra_1:
    image: cassandra:4.0
    container_name: cassandra_1_container
    networks:
      - default_net
    environment: &environment
      CASSANDRA_LISTEN_ADDRESS: 
      CASSANDRA_BROADCAST_ADDRESS: 
      CASSANDRA_RPC_ADDRESS: 
      CASSANDRA_START_RPC: 
      CASSANDRA_SEEDS: "cassandra_1"
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_DC: DataCenter
      CASSANDRA_RACK: Rack
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra-db-volume:/var/lib/cassandra
      - ./etc:/etc/cassandra
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9042/health"]
      interval: 30s
      timeout: 20s
      retries: 3

  cassandra_2:
    image: cassandra:4.0
    container_name: cassandra_2_container
    networks:
      - default_net
    environment: *environment
    volumes:
      - cassandra-db-volume:/var/lib/cassandra
      - ./etc:/etc/cassandra
    ports:
      - "9043:9042"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9042/health"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  default_net:
volumes:
  cassandra-db-volume:
