FROM apache/airflow:2.3.0

# Change to root user
USER root

# Install OpenJDK-11
RUN apt update && apt-get install -y openjdk-11-jdk && apt-get install -y ant && apt-get clean

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

# Change user and set work directory
USER airflow
WORKDIR /app

# Install requirements
RUN pip install --upgrade pip
RUN pip install --no-cache-dir apache-airflow-providers-apache-spark
