version: '3'

services:
    # Apache Spark master and two workers
    spark:
        image: docker.io/bitnami/spark:3
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/scripts:/usr/local/spark/scripts
            - ../spark/resources:/usr/local/spark/resources
        ports:
            - '8080:8080'
            - '7077:7077'
    spark-worker-1:
        image: docker.io/bitnami/spark:3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/scripts:/usr/local/spark/scripts
            - ../spark/resources:/usr/local/spark/resources
    spark-worker-2:
        image: docker.io/bitnami/spark:3
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:
            - ../spark/scripts:/usr/local/spark/scripts
            - ../spark/resources:/usr/local/spark/resources
    # Apache Airflow master, scheduler, worker and postgres database
    airflow:
        image: docker.io/bitnami/airflow:2
        environment: 
            - AIRFLOW_DATABASE_NAME=airflow
            - AIRFLOW_DATABASE_USERNAME=airflow
            - AIRFLOW_DATABASE_PASSWORD=airflow
            - AIRFLOW_EXECUTOR=CeleryExecutor
            #- AIRFLOW_WEBSERVER_PORT_NUMBER=8181
        volumes:
            - ../airflow/dags:/usr/local/airflow/dags
        ports:
            - '8181:8181'
    airflow-scheduler:
        image: docker.io/bitnami/airflow-scheduler:2
        environment: 
            - AIRFLOW_DATABASE_NAME=airflow
            - AIRFLOW_DATABASE_USERNAME=airflow
            - AIRFLOW_DATABASE_PASSWORD=airflow
            - AIRFLOW_EXECUTOR=CeleryExecutor
            - AIRFLOW_WEBSERVER_HOST=airflow
    airflow-worker:
        image: docker.io/bitnami/airflow:2
        environment: 
            - AIRFLOW_DATABASE_NAME=airflow
            - AIRFLOW_DATABASE_USERNAME=airflow
            - AIRFLOW_DATABASE_PASSWORD=airflow
            - AIRFLOW_EXECUTOR=CeleryExecutor
            - AIRFLOW_WEBSERVER_HOST=airflow
    postgresql:
        image: postgres:10
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
