version: '3.9'

services:
  cassandra-1:
    image: cassandra:4.0
    container_name: cassandra_1_container
    networks:
      - default_net
    ports:
      - 9042:9042
    volumes:
      - cassandra-db-volume:/var/lib/cassandra
      - ./schema.cql:/schema.cql
    environment: &environment
      #CASSANDRA_LISTEN_ADDRESS: 
      #CASSANDRA_BROADCAST_ADDRESS: 
      #CASSANDRA_RPC_ADDRESS: 
      #CASSANDRA_START_RPC: 
      #CASSANDRA_SEEDS: "cassandra_1"
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 128M
      CASSANDRA_USER: cassandra
      CASSANDRA_HOST: cassandra
      CASSANDRA_PASSWORD: 
      CASSANDRA_CLUSTER_NAME: CassandraCluster
      CASSANDRA_NUM_TOKENS: 128
      CASSANDRA_DATACENTER: DataCenter1
      CASSANDRA_RACK: Rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 30s
      timeout: 20s
      retries: 3

  cassandra-init:
    image: cassandra:4.0
    container_name: cassandra_init
    depends_on:
      cassandra-1:
        condition: service_healthy
    volumes:
      - ./schema.cql:/schema.cql 
    command: /bin/bash -c "sleep 45 && echo loading cassandra keyspace && cqlsh cassandra -u cassandra -p cassandra -f /schema.cql"

networks:
  default_net:
volumes:
  cassandra-db-volume: