FROM apache/airflow:2.3.0

# Change to root user
USER root

# Install OpenJDK-11
RUN apt update && apt-get install -y openjdk-11-jdk && apt-get install -y ant && apt-get clean

# Set JAVA_HOME
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-amd64/
RUN export JAVA_HOME

# Set SPARK_HOME
# ENV SPARK_HOME /usr/lib/spark
# RUN export SPARK_HOME

# Change user
USER airflow

# Install requirements
COPY requirements_airflow.txt ./requirements_airflow.txt
RUN pip install --upgrade pip
RUN pip install --trusted-host pypi.python.org --no-cache-dir -r requirements_airflow.txt